# Generated by Django 6.0.3 on 2026-03-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="prénom")),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=100, verbose_name="nom"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email"
                    ),
                ),
                (
                    "is_invited",
                    models.BooleanField(default=True, verbose_name="invité classique"),
                ),
                (
                    "is_vip",
                    models.BooleanField(default=False, verbose_name="invité VIP"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le"),
                ),
            ],
            options={
                "verbose_name": "invité",
                "verbose_name_plural": "invités",
                "ordering": ["first_name", "last_name"],
            },
        ),
    ]
