# Generated by Django 6.0.3 on 2026-03-15 11:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("guests", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecialDemand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "demand_type",
                    models.CharField(
                        choices=[
                            ("witness", "Témoin"),
                            ("maid_of_honor", "Femme d'honneur"),
                            ("best_man", "Homme d'honneur"),
                        ],
                        max_length=30,
                        verbose_name="type de demande",
                    ),
                ),
                (
                    "request_owner",
                    models.CharField(
                        choices=[
                            ("groom", "Marié"),
                            ("bride", "Mariée"),
                            ("couple", "Les deux"),
                        ],
                        default="couple",
                        max_length=20,
                        verbose_name="demande portée par",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "final_question",
                    models.CharField(
                        default="Alors… accepterais-tu ? 💍",
                        max_length=255,
                        verbose_name="question finale",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("accepted", "Acceptée"),
                            ("declined", "Refusée"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                (
                    "notify_emails",
                    models.TextField(
                        blank=True,
                        help_text="Adresses email séparées par des virgules",
                        verbose_name="emails à notifier",
                    ),
                ),
                (
                    "responded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="répondu le"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_special_demands",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créée par",
                    ),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="special_demands",
                        to="guests.guest",
                        verbose_name="invité",
                    ),
                ),
            ],
            options={
                "verbose_name": "demande spéciale",
                "verbose_name_plural": "demandes spéciales",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SpecialDemandSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(verbose_name="position")),
                (
                    "title",
                    models.CharField(blank=True, max_length=255, verbose_name="titre"),
                ),
                ("text", models.TextField(verbose_name="texte")),
                (
                    "image",
                    models.ImageField(
                        upload_to="specialdemands/slides/", verbose_name="image"
                    ),
                ),
                (
                    "special_demand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slides",
                        to="specialdemands.specialdemand",
                        verbose_name="demande spéciale",
                    ),
                ),
            ],
            options={
                "verbose_name": "slide de demande spéciale",
                "verbose_name_plural": "slides de demandes spéciales",
                "ordering": ["position"],
                "unique_together": {("special_demand", "position")},
            },
        ),
    ]
