# Generated by Django 6.0.3 on 2026-03-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specialdemands", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specialdemand",
            name="notify_emails",
            field=models.TextField(
                blank=True,
                default="boliobi93@gmail.com, leslie.sokeng@gmail.com",
                help_text="Adresses email séparées par des virgules",
                verbose_name="emails à notifier",
            ),
        ),
    ]
