# Generated by Django 6.0.3 on 2026-03-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specialdemands", "0002_alter_specialdemand_notify_emails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specialdemand",
            name="notify_emails",
            field=models.TextField(
                blank=True,
                default="nous@leslieniboli.fr",
                help_text="Adresses email séparées par des virgules",
                verbose_name="emails à notifier",
            ),
        ),
    ]
